spring:
  datasource:
    url: jdbc:mysql://47.107.186.18:3306/p2p?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: scott
    password: tiger654321
  redis:
    database: 0
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
